#ifndef BYTECODE_COMMAND_HH
# define BYTECODE_COMMAND_HH

# include <command/libcommand.hh>

# include <compile/libcompile.hh>

# include <execute/libexecute.hh>

namespace execute
{
    REGULAR_COMMAND("-d|--readable_dump",
                    "Dump readable executable generated by the compiler",
                    "-c|--compile", dump_readable_internal);

    REGULAR_COMMAND("-e|--execute",
                    "Execute input file",
                    "-c|--compile", execute_internal);
} // namespace execute

#endif /* !BYTECODE_COMMAND_HH */
