#ifndef BYTECODE_COMMAND_HH
# define BYTECODE_COMMAND_HH

# include <command/libcommand.hh>

# include <compile/libcompile.hh>

namespace bytecode
{
    REGULAR_COMMAND("-d|--readable_dump",
                    "Dump readable executable generated by the compiler",
                    "-c|--compile", dump_readable_internal);
} // namespace bytecode

#endif /* !BYTECODE_COMMAND_HH */
